tc39/proposal-intl-segmenter

spec.html
=> Fix issues/34 by better specify %SegmentIteratorPrototype%

spec.html
=> Normative: Clarify breakType values

spec.html
The goal is to allow for easier usability and alignment with the
String.prototype.codePoints proposal.
By @FrankYFTang
Closes #27
=> Normative: Include position in segment object

spec.html
@littledan @mathiasbynens @Ms2ger
=> Editorial: Specify table order per https://github.com/tc39/ecma402/issues/264

spec.html
=> Restore correct forwards iteration done check

.gitignore, README.md, spec.html
=> Remove support for { granularity: 'line' }

spec.html
Missing parts in https://github.com/tc39/proposal-intl-segmenter/pull/60
@littledan @mathiasbynens @litherum  @zbraniecki
=> Follow up PR to fix missing changes in pull/60

README.md, spec.html
=> Clarify the definition of "index"

README.md
=> Editorial: Improve examples

biblio.json, package.json, spec.html
=> Editorial: Update to match ECMA-402 conventions

README.md, biblio.json, spec.html
=> Update from boundary iteration to segment iteration

spec.html
=> Editorial: Add a note explaining "word-like"

spec.html
=> Editorial: Include Segmenter implementation dependence in Annex A

spec.html
=> Editorial: Address review feedback

spec.html
To sync with https://github.com/tc39/ecma402/pull/430
@gibson042
=> change the initial value of the @@toStringTag

spec.html
Put the part that we agreed in #107 here.
=> Editorial change from #107

README.md, spec.html
Improves correspondence with RegExp match objects
Fixes #116
Fixes #96
=> Normative: Add "input" to segment data objects

spec.html
=> Editorial: Change "be this value" to "be the this value"

spec.html
=> Editorial: Use dotted intrinsic form

README.md, biblio.json, spec.html
=> Editorial: Update ToInteger reference and explanation

README.md
=> Advance to Stage 4
